import type { Metadata } from 'next'
import { Inter,Ubuntu } from 'next/font/google'
import './globals.css'
import { Toaster } from "@/components/ui/toaster"

const inter = Ubuntu({
  subsets: ['latin'],
  weight: '300'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main>{children}</main>
        <Toaster />
        </body>
      
    </html>
  )
}
